{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red70\green137\blue204;\red0\green0\blue0;\red255\green255\blue255;
\red194\green126\blue101;}
{\*\expandedcolortbl;;\cssrgb\c33725\c61176\c83922;\cssrgb\c0\c0\c0;\cssrgb\c100000\c100000\c100000;
\cssrgb\c80784\c56863\c47059;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 name\cf4 \strokec4 : \cf5 \strokec5 SNL-environment\cf4 \cb1 \strokec4 \
\
\cf2 \cb3 \strokec2 channels\cf4 \strokec4 :\cb1 \
\pard\pardeftab720\partightenfactor0
\cf4 \cb3  - \cf5 \strokec5 conda-forge\cf4 \cb1 \strokec4 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \cb3 \strokec2 dependencies\cf4 \strokec4 :\cb1 \
\pard\pardeftab720\partightenfactor0
\cf4 \cb3 - \cf5 \strokec5 pandas\cf4 \cb1 \strokec4 \
\cb3 - \cf5 \strokec5 numpy\cf4 \cb1 \strokec4 \
\cb3 - \cf5 \strokec5 ipywidgets\cf4 \cb1 \strokec4 \
\cb3 - \cf5 \strokec5 matplotlib=3.2.2\cf4 \cb1 \strokec4 \
\cb3 - \cf5 \strokec5 bqplot=0.12.30\cf4 \cb1 \strokec4 \
}